### ISSUE TITLE
Cannot download the file "msmarco-v2.pickle"

### ISSUE THREAD

**Issue by ChuanMeng** [suchanadatta/qppBERT-PL#1]
Hi Suchana,
I'm quite interested in your work.
I found the link for downloading the file "**msmarco-v2.pickle**" in this repo seems to be wrong. Could you please fix it?
![image](https://user-images.githubusercontent.com/37291827/200565448-5f16c7c0-7dcd-47ae-846f-bd30281b2437.png)

Cheers,
Chuan

**Comment by suchanadatta** [comment]
Hi Chuan,
Thanks for your interest. Could you please try downloading now? Should be fine.

Best,
Suchana

**Comment by ChuanMeng** [comment]
Hi Suchana,
I just checked it again. The download link for "collection" is still for the index "msmarco-v2.pisa.tar.gz" instead of  "msmarco-v2.pickle".

Cheers,
Chuan

**Comment by suchanadatta** [comment]
Hey Chuan,
Sorry for the confusion. I understood that the link was not working in your end. sorry!
Here's the pickle dump for V2 : https://drive.google.com/file/d/12dcXWHiJy0adTuhHWw72DobjZUQDWP0j/view?usp=share_link

**Comment by ChuanMeng** [comment]
Thank you Suchana. The link you sent works :-).
