### ISSUE TITLE
The question about the iterator for the test set

### ISSUE THREAD

**Issue by ChuanMeng** [suchanadatta/qppBERT-PL#3]
Hi Suchana,
I also had a question about the iterator for the test set.
As shown in eval.py (line 201), "for test_i in range(len(q_dict) * args.chunk_per_query * args.batch_size)" set the number of iterations to “len(q_dict) * args.chunk_per_query * args.batch_size”. However, I think the total number of iterations on the test set should be  “len(q_dict) * args.chunk_per_query" because the iterator would iterate 25 times per query (each iteration returns 4 documents, and iterating 25 times represents the finish of one query). Additional adding " * args.batch_size ", I think, would produce duplicated results for the test set.

![image](https://user-images.githubusercontent.com/37291827/200871375-b34b10c9-a72f-4dd6-918a-70f22034b8f1.png)

**Comment by suchanadatta** [comment]
Hi Chuan,
Yes, you are correct. That additional count was for other experiments. Sorry for the inconvenience, it's corrected now.
Thanks for pointing :+1:

**Comment by ChuanMeng** [comment]
Thank you for your reply.
Also, I think there is the same issue in the train.py (line 120). But I think the "* args.batch_size" here can be explained as the number of epochs? The args.batch_size is 4, so the model would train for 4 epochs. Is my understanding correct?
![image](https://user-images.githubusercontent.com/37291827/201098774-06e8aa4d-fbf6-4734-8179-0074ffb3db88.png)

Cheers.
Chuan

**Comment by suchanadatta** [comment]
Absolutely, that's the idea here.

Bests,
Suchana
