### ISSUE TITLE
Lack of the BM25 run file

### ISSUE THREAD

**Issue by ChuanMeng** [suchanadatta/qppBERT-PL#4]
Hi Suchana,
I hope you are doing well and thank you for answering my previous questions.
For evaluating the QPP model, my understanding is that we need two lists, one is predicted MAP values and the other one is actual MAP performance. 
The repo already has the predicted QPP values from the proposed model, but doesn't contain the BM25 run file that can be used to calculate the actual MAP performance.
Could you please share the BM25 run files on the test set?

Thank you in advance!

Cheers,
Chuan

**Comment by suchanadatta** [comment]
Hi CHuan,
Sincere apologies for the delay, I somehow missed the email notification!
Anyway, which test set are you working on? Just let me know. I can certainly provide the BM25 result.
--suchana
